services:
  # Backend API service
  - type: pserv
    name: bet-analyser-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: bun install && npx prisma generate && npx prisma migrate deploy
    startCommand: bun run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bet-analyser-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SETUP_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://bet-analyser.onrender.com

  # Frontend service
  - type: web
    name: bet-analyser-frontend
    runtime: static
    plan: free
    region: singapore
    buildCommand: cd frontend && bun install && bun run build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.bet-analyser.onrender.com

# Database
databases:
  - name: bet-analyser-db
    plan: free
    region: singapore
    databaseName: betanalyser
    ipAllowList: [] # only allow internal connections
