services:
  # Backend API service
  - type: web
    name: bet-analyzer-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: yarn install && npx prisma generate && npx prisma migrate deploy
    startCommand: yarn run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bet-analyzer-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SETUP_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://bet-analyzer.onrender.com

  # Frontend service
  - type: web
    name: bet-analyzer
    runtime: static
    buildCommand: cd frontend && yarn install && yan run build
    staticPublishPath: ./build
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://bet-analyzer-api.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
# Database
databases:
  - name: bet-analyzer-db
    plan: free
    region: singapore
    databaseName: betanalyser
    ipAllowList: [] # only allow internal connections
